In [ ]:
pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 55.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 27.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 75.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 64.6 MB/s eta 0:00:00


In [1]:
import numpy as np
import pandas as pd
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer

data=pd.read_csv('IMDB Dataset.csv')
data

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [2]:
data['cleaned_review'] = data['review'].apply(lambda text: re.sub('<.*?>', '', text))  # Remove HTML tags
data['cleaned_review'] = data['cleaned_review'].apply(lambda text: re.sub('[^a-zA-Z0-9\s]', '', text))  # Remove non-alphanumeric characters
data['cleaned_review'] = data['cleaned_review'].apply(lambda text: re.sub('\s+', ' ', text).strip())  # Remove extra whitespace
data['cleaned_review'] = data['cleaned_review'].apply(lambda text: text.lower())  # Convert to lowercase
for review in data['cleaned_review'].head(10):
    print(review)
    print('---')

one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty picture

In [3]:
# Download required resources (one-time setup)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [4]:
file_path = '/content/IMDB Dataset.csv'
data = pd.read_csv('IMDB Dataset.csv')
reviews = data['review'].tolist()
labels = data['sentiment'].tolist()

# Tokenize the dataset
for review in data['review'].head(100):
    tokens = word_tokenize(review)
    print(tokens)
    print('---') #tokenized output


['One', 'of', 'the', 'other', 'reviewers', 'has', 'mentioned', 'that', 'after', 'watching', 'just', '1', 'Oz', 'episode', 'you', "'ll", 'be', 'hooked', '.', 'They', 'are', 'right', ',', 'as', 'this', 'is', 'exactly', 'what', 'happened', 'with', 'me.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'The', 'first', 'thing', 'that', 'struck', 'me', 'about', 'Oz', 'was', 'its', 'brutality', 'and', 'unflinching', 'scenes', 'of', 'violence', ',', 'which', 'set', 'in', 'right', 'from', 'the', 'word', 'GO', '.', 'Trust', 'me', ',', 'this', 'is', 'not', 'a', 'show', 'for', 'the', 'faint', 'hearted', 'or', 'timid', '.', 'This', 'show', 'pulls', 'no', 'punches', 'with', 'regards', 'to', 'drugs', ',', 'sex', 'or', 'violence', '.', 'Its', 'is', 'hardcore', ',', 'in', 'the', 'classic', 'use', 'of', 'the', 'word.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'It', 'is', 'called', 'OZ', 'as', 'that', 'is', 'the', 'nickname', 'given', 'to', 'the', 'Oswald', 'Maximum', 'Security', 'State', 'Penitentary', '.', 

In [ ]:
# Remove stop words from the dataset
stop_words = set(stopwords.words('english'))

for review in data['review'].head(100):
    tokens = word_tokenize(review)
    filtered_tokens = [token for token in tokens if token.lower() not in stop_words]
    print(filtered_tokens)
    print('---') # Now the output of stop words removal for 100 reviews.

['One', 'reviewers', 'mentioned', 'watching', '1', 'Oz', 'episode', "'ll", 'hooked', '.', 'right', ',', 'exactly', 'happened', 'me.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'first', 'thing', 'struck', 'Oz', 'brutality', 'unflinching', 'scenes', 'violence', ',', 'set', 'right', 'word', 'GO', '.', 'Trust', ',', 'show', 'faint', 'hearted', 'timid', '.', 'show', 'pulls', 'punches', 'regards', 'drugs', ',', 'sex', 'violence', '.', 'hardcore', ',', 'classic', 'use', 'word.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'called', 'OZ', 'nickname', 'given', 'Oswald', 'Maximum', 'Security', 'State', 'Penitentary', '.', 'focuses', 'mainly', 'Emerald', 'City', ',', 'experimental', 'section', 'prison', 'cells', 'glass', 'fronts', 'face', 'inwards', ',', 'privacy', 'high', 'agenda', '.', 'Em', 'City', 'home', 'many', '..', 'Aryans', ',', 'Muslims', ',', 'gangstas', ',', 'Latinos', ',', 'Christians', ',', 'Italians', ',', 'Irish', '....', 'scuffles', ',', 'death', 'stares', ',', 'dodgy', 'dealings',

In [ ]:
#pos tags
for review in data['review'].head(10):
    tokens = word_tokenize(review)
    pos_tags = pos_tag(tokens)
    print(pos_tags)
    print('---')

[('One', 'CD'), ('of', 'IN'), ('the', 'DT'), ('other', 'JJ'), ('reviewers', 'NNS'), ('has', 'VBZ'), ('mentioned', 'VBN'), ('that', 'IN'), ('after', 'IN'), ('watching', 'VBG'), ('just', 'RB'), ('1', 'CD'), ('Oz', 'NNP'), ('episode', 'NN'), ('you', 'PRP'), ("'ll", 'MD'), ('be', 'VB'), ('hooked', 'VBN'), ('.', '.'), ('They', 'PRP'), ('are', 'VBP'), ('right', 'JJ'), (',', ','), ('as', 'IN'), ('this', 'DT'), ('is', 'VBZ'), ('exactly', 'RB'), ('what', 'WP'), ('happened', 'VBD'), ('with', 'IN'), ('me.', 'JJ'), ('<', 'NNP'), ('br', 'NN'), ('/', 'NNP'), ('>', 'NNP'), ('<', 'NNP'), ('br', 'NN'), ('/', 'NNP'), ('>', 'VBZ'), ('The', 'DT'), ('first', 'JJ'), ('thing', 'NN'), ('that', 'WDT'), ('struck', 'VBD'), ('me', 'PRP'), ('about', 'IN'), ('Oz', 'NNP'), ('was', 'VBD'), ('its', 'PRP$'), ('brutality', 'NN'), ('and', 'CC'), ('unflinching', 'JJ'), ('scenes', 'NNS'), ('of', 'IN'), ('violence', 'NN'), (',', ','), ('which', 'WDT'), ('set', 'VBP'), ('in', 'IN'), ('right', 'NN'), ('from', 'IN'), ('the', '

In [ ]:
#lemmatization
lemmatizer = WordNetLemmatizer()

for review in data['review'].head(10):
    tokens = word_tokenize(review)
    lemmas = [lemmatizer.lemmatize(token) for token in tokens]
    print(lemmas)
    print('---')


['One', 'of', 'the', 'other', 'reviewer', 'ha', 'mentioned', 'that', 'after', 'watching', 'just', '1', 'Oz', 'episode', 'you', "'ll", 'be', 'hooked', '.', 'They', 'are', 'right', ',', 'a', 'this', 'is', 'exactly', 'what', 'happened', 'with', 'me.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'The', 'first', 'thing', 'that', 'struck', 'me', 'about', 'Oz', 'wa', 'it', 'brutality', 'and', 'unflinching', 'scene', 'of', 'violence', ',', 'which', 'set', 'in', 'right', 'from', 'the', 'word', 'GO', '.', 'Trust', 'me', ',', 'this', 'is', 'not', 'a', 'show', 'for', 'the', 'faint', 'hearted', 'or', 'timid', '.', 'This', 'show', 'pull', 'no', 'punch', 'with', 'regard', 'to', 'drug', ',', 'sex', 'or', 'violence', '.', 'Its', 'is', 'hardcore', ',', 'in', 'the', 'classic', 'use', 'of', 'the', 'word.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'It', 'is', 'called', 'OZ', 'a', 'that', 'is', 'the', 'nickname', 'given', 'to', 'the', 'Oswald', 'Maximum', 'Security', 'State', 'Penitentary', '.', 'It', 'focus

In [5]:
#Spliting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(reviews, labels, test_size=0.3, random_state=42)

In [6]:
# Feature Extraction
# We will have format in which we will get all the columns of the words and wordcount
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)
#We will take the take the top 500 words else we will get many words

In [ ]:
X = cv.fit_transform(data['review']).toarray()

In [ ]:
X.shape

(50000, 1000)

In [7]:
y = data.iloc[:, -1].values
y

array(['positive', 'positive', 'positive', ..., 'negative', 'negative',
       'negative'], dtype=object)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec
data_subset = data.head(100)
# Bag of Words (BoW) feature extraction
bow_vectorizer = CountVectorizer()
bow_features = bow_vectorizer.fit_transform(data_subset['review'])

# Print the output
print("Bag of Words (BoW) features:")
print(bow_features.toarray())

Bag of Words (BoW) features:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]]


In [ ]:
# TF-IDF feature extraction
tfidf_vectorizer = TfidfVectorizer()
tfidf_features = tfidf_vectorizer.fit_transform(data_subset['review'])
print("TF-IDF features:")
print(tfidf_features.toarray())

TF-IDF features:
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.06630969 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.03485912 ... 0.         0.         0.        ]]


In [ ]:
# Word Embeddings (Word2Vec) feature extraction
sentences = [review.split() for review in data_subset['review']]
word2vec_model = Word2Vec(sentences, min_count=1)
word2vec_features = [word2vec_model.wv[words] for words in sentences]
print("Word Embeddings (Word2Vec) features:")
for feature in word2vec_features:
    print(feature)

Word Embeddings (Word2Vec) features:
[[-1.0946652e-02  3.0824548e-02  1.7510737e-04 ... -2.6160294e-02
   1.0165717e-02  4.7405697e-03]
 [-1.6713697e-01  4.1623214e-01 -1.6367676e-02 ... -2.9976702e-01
   6.0205795e-02  1.9112481e-03]
 [-1.9723745e-01  4.8672125e-01 -4.7039669e-03 ... -3.5961500e-01
   6.3560165e-02  1.6646115e-02]
 ...
 [-4.4737957e-02  1.0822355e-01  2.9843985e-03 ... -8.3247267e-02
   1.9476136e-02  9.6656755e-03]
 [ 4.8046741e-03 -2.5801887e-03  9.8248953e-03 ... -9.5961839e-03
   7.5926711e-03 -8.6770104e-03]
 [ 6.9798552e-04  9.2991656e-03  6.3329889e-03 ...  1.9202628e-03
   4.9895970e-03 -7.7757114e-03]]
[[-0.03105798  0.06673005  0.00683    ... -0.03699104  0.01183655
   0.00997566]
 [-0.00718672  0.00959381  0.00697163 ... -0.02281186 -0.00359524
  -0.00927506]
 [-0.03487922  0.07783096 -0.00846316 ... -0.05977757  0.01978707
   0.00771045]
 ...
 [ 0.00551564  0.01197308  0.00848995 ... -0.0033644  -0.00537193
   0.0099979 ]
 [-0.03546285  0.08416808 -0.00629

In [9]:
#Training
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

In [10]:
# Naive Bayes
from sklearn.naive_bayes import MultinomialNB
nb_vectorizer = CountVectorizer()
X_train_nb = nb_vectorizer.fit_transform(X_train)
X_test_nb = nb_vectorizer.transform(X_test)
nb_model = MultinomialNB()
nb_model.fit(X_train_nb, y_train)
nb_predictions = nb_model.predict(X_test_nb)
nb_accuracy = accuracy_score(y_test, nb_predictions)
print("Naive Bayes Accuracy:", nb_accuracy)

Naive Bayes Accuracy: 0.8485333333333334


In [ ]:
# Recurrent Neural Networks (RNN)
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)
X_train_rnn = tokenizer.texts_to_sequences(X_train)
X_test_rnn = tokenizer.texts_to_sequences(X_test)
vocab_size = len(tokenizer.word_index) + 1
max_length = max(len(sequence) for sequence in X_train_rnn)
X_train_rnn = pad_sequences(X_train_rnn, maxlen=max_length, padding='post')
X_test_rnn = pad_sequences(X_test_rnn, maxlen=max_length, padding='post')
le = LabelEncoder()
y_train_rnn = le.fit_transform(y_train)
y_test_rnn = le.transform(y_test)
rnn_model = Sequential()
rnn_model.add(Embedding(vocab_size, 100, input_length=max_length))
rnn_model.add(LSTM(100))
rnn_model.add(Dense(1, activation='sigmoid'))
rnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
rnn_model.fit(X_train_rnn, y_train_rnn, validation_data=(X_test_rnn, y_test_rnn), epochs=5)
_, rnn_accuracy = rnn_model.evaluate(X_test_rnn, y_test_rnn)
print("RNN Accuracy:", rnn_accuracy)

Epoch 1/5
1094/1094 [==============================] - 4134s 4s/step - loss: 0.6932 - accuracy: 0.5053 - val_loss: 0.6932 - val_accuracy: 0.4941
Epoch 2/5
1094/1094 [==============================] - 4062s 4s/step - loss: 0.6932 - accuracy: 0.4965 - val_loss: 0.6933 - val_accuracy: 0.4941
Epoch 3/5
1094/1094 [==============================] - 4027s 4s/step - loss: 0.6932 - accuracy: 0.4964 - val_loss: 0.6932 - val_accuracy: 0.4941
Epoch 4/5
1094/1094 [==============================] - 4009s 4s/step - loss: 0.6931 - accuracy: 0.5037 - val_loss: 0.6931 - val_accuracy: 0.5059
Epoch 5/5
469/469 [==============================] - 300s 640ms/step - loss: 0.6931 - accuracy: 0.5059
RNN Accuracy: 0.5059333443641663


In [ ]:
nb_accuracy = accuracy_score(y_test, nb_predictions)
nb_precision = precision_score(y_test, nb_predictions, average='weighted')
nb_recall = recall_score(y_test, nb_predictions, average='weighted')
nb_f1 = f1_score(y_test, nb_predictions, average='weighted')
print("Naive Bayes Precision:", nb_precision)
print("Naive Bayes Recall:", nb_recall)
print("Naive Bayes F1 Score:", nb_f1)

Naive Bayes Precision: 0.8501685739438425
Naive Bayes Recall: 0.8485333333333334
Naive Bayes F1 Score: 0.8484281997744445


In [25]:
# New unseen text samples
new_samples = [
    "The acting was terrible and the plot was confusing.",
    "I didn't enjoy the movie at all, waste of time.",
]
new_samples_nb = nb_vectorizer.transform(new_samples)
# Predict sentiment labels using Naive Bayes
nb_predictions = nb_model.predict(new_samples_nb)

# Mapping sentiment labels to sentiment expressions
sentiment_mapping = {
    0: "negative",
    1: "positive"
}


# Print predictions for new samples
for i, sample in enumerate(new_samples):
    print(f"Sample {i+1}: {sample} - Sentiment: {'Positive' if nb_predictions[i] == 1 else 'Negative'}")

Sample 1: The acting was terrible and the plot was confusing. - Sentiment: Negative
Sample 2: I didn't enjoy the movie at all, waste of time. - Sentiment: Negative
